# Generated by Django 6.1.1 on 2026-09-22 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Segunda', 'Segunda-feira'), ('Terça', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'Sexta-feira')], max_length=20, verbose_name='Dia da Semana')),
                ('turno', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde')], max_length=10, verbose_name='Turno')),
                ('equipe', models.CharField(max_length=255, verbose_name='Integrantes (Ex: Kennyo - Gabi - Thayane)')),
            ],
            options={
                'verbose_name': 'Escala de Trabalho',
                'verbose_name_plural': 'Escalas de Trabalho',
            },
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('curso', models.CharField(max_length=150, verbose_name='Curso / Graduação')),
                ('situacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Situação / Função no Projeto')),
                ('foto', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Foto do Perfil')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes do Projeto',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Local')),
                ('distrito', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito Sanitário')),
                ('categoria', models.CharField(choices=[('Esporte e Lazer', 'Esporte e Lazer'), ('Saúde', 'Saúde'), ('Educação', 'Educação'), ('Religião', 'Religião'), ('Cultura', 'Cultura'), ('Comércio', 'Comércio'), ('Administrativo', 'Administrativo')], max_length=50, verbose_name='Categoria')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('lon', models.FloatField(verbose_name='Longitude')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status de Infraestrutura')),
                ('cor', models.CharField(default='purple', max_length=20, verbose_name='Cor do Marcador')),
                ('icone', models.CharField(default='hospital', max_length=50, verbose_name='Ícone (FontAwesome)')),
                ('foto', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Foto (Drive ou Externa)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Local')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais do Mapa',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Atividade')),
                ('data', models.DateField(verbose_name='Data da Atividade')),
                ('descricao', models.TextField(verbose_name='Descrição da Atividade')),
                ('foto', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Imagem')),
                ('cor_borda', models.CharField(default='#4C2059', max_length=20, verbose_name='Cor de Destaque')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades e Eventos',
                'ordering': ['-data'],
            },
        ),
    ]
