# Generated by Django 6.1.1 on 2026-09-22 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='integrante',
            options={},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={},
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='cor_borda',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='foto',
        ),
        migrations.AddField(
            model_name='atividade',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Foto/Evidência do Evento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.local', verbose_name='Local Relacionado'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título do Evento'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='foto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='situacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='categoria',
            field=models.CharField(default='Saúde', max_length=100),
        ),
        migrations.AlterField(
            model_name='local',
            name='cor',
            field=models.CharField(default='purple', max_length=30),
        ),
        migrations.AlterField(
            model_name='local',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='foto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='icone',
            field=models.CharField(default='hospital', max_length=30),
        ),
        migrations.AlterField(
            model_name='local',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='local',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='local',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='local',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
