# Generated by Django 6.1.1 on 2026-09-23 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_atividade_options_alter_integrante_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalatrabalho',
            options={'ordering': ['dia_semana', 'horario_inicio'], 'verbose_name': 'Escala de Trabalho', 'verbose_name_plural': 'Escalas de Trabalho'},
        ),
        migrations.RemoveField(
            model_name='escalatrabalho',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='escalatrabalho',
            name='equipe',
        ),
        migrations.AddField(
            model_name='escalatrabalho',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='Segunda-feira', max_length=20, null=True, verbose_name='Dia da Semana'),
        ),
        migrations.AddField(
            model_name='escalatrabalho',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Término'),
        ),
        migrations.AddField(
            model_name='escalatrabalho',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Início'),
        ),
        migrations.AddField(
            model_name='escalatrabalho',
            name='integrante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='core.integrante', verbose_name='Integrante'),
        ),
        migrations.AddField(
            model_name='escalatrabalho',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='core.local', verbose_name='Local de Atuação'),
        ),
        migrations.AddField(
            model_name='escalatrabalho',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='escalatrabalho',
            name='turno',
            field=models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Integral', 'Integral')], default='Manhã', max_length=20, verbose_name='Turno'),
        ),
    ]
