# Generated by Django 6.1.1 on 2026-09-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_escalatrabalho_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF (Apenas números ou formatado)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Autorizado')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Autorização Ativa')),
            ],
            options={
                'verbose_name': 'Usuário Autorizado',
                'verbose_name_plural': 'Usuários Autorizados (White-list)',
            },
        ),
    ]
